#!/bin/bash
#
# SPDX-FileCopyrightText: 2020-2024 KUNBUS GmbH
#
# SPDX-License-Identifier: GPL-2.0-or-later
#

usage() {
	cat <<- __EOF__
	usage: $(basename $0) [-f]

	Generate an archive of useful information for debugging.

	Options:
	  -f    Skip user interaction
	  -h    Show this help
	__EOF__

	exit ${1:-0}
}

FORCE=0

while getopts ":fh" opt; do
	case "${opt}" in
	f)
		FORCE=1
		;;
	h)
		usage
		;;
	*)
		usage 1 >&2
		;;
	esac

done

if [ "$FORCE" != "1" ]; then
	read -rp "The report will be generated as a compressed TAR file, which
can be extracted with command: tar -zxvf xxx.tar.gz in linux or 7zip in Windows.
And then some inspection can be done before it is sent to support@kunbus.com.

Are you going to continue (N/y)? " -n 1 t_ant

	if [ "$t_ant" != "y" ] && [ "$t_ant" != "Y" ]; then
		echo
		exit 0
	fi
	echo
fi

echo "report generating..."
SOSFILE=$(sudo sos report -o revpi,revpi-eep,revpi-codesys --batch | grep "/sosreport-.*\.tar" | sed -e 's/^[ \t]*//')
echo
echo "Your report has been generated and saved in:"
echo "$SOSFILE"
echo

if [ "$FORCE" != "1" ]; then
	read -rp "To make the report have better accessibility, the ownership of the report
can be changed to the current user.

Are you going to proceed(N/y)? " -n 1 t_ant
	if [ "$t_ant" != "y" ] && [ "$t_ant" != "Y" ]; then
		echo
		exit 0
	fi
	echo
fi

sudo chown "$USER" "$SOSFILE"
echo "The ownership of $SOSFILE has been changed to user: $USER"
