#!/bin/bash
#
# SPDX-License-Identifier: GPL-2.0
#
# Copyright 2020-2023 KUNBUS GmbH
#

sos_tmp_dir=/tmp
sos_owner=$USER
ret=1
force=0

while getopts ":fhd:o:" OPTION; do
	case ${OPTION} in
	f)
		force=1
		;;
	d)
		sos_tmp_dir="$OPTARG"
		;;
	o)
		sos_owner="$OPTARG"
		;;
	h)
		ret=0
		;&
	*)
		echo "Usage: revpi-sos [OPTION...]"
		echo "	-d	DIRECTORY Specify target directory for generated report. If omitted /tmp is used"
		echo "	-o	USER[:GROUP]	Specify name or uid of user and/or group that will be made owner of generated report."
		echo "	-f	execute without confirmation"
		echo "	-h	give this help list"
		exit $ret
		;;
	esac

done

timestamp=$(date +"%s")
sos_tmp_dir="$sos_tmp_dir/revpi-sos-$timestamp"
sudo mkdir -p "$sos_tmp_dir"
sudo chown -R "$sos_owner" "$sos_tmp_dir"

if [ "$force" != "1" ]; then
	read -rp "The report will be generated under folder $sos_tmp_dir in a .tar.xz file, which
can be extracted with command: tar -Jxvf xxx.tar.xz in linux or 7zip in Windows.
And then some inspection can be done before it is sent to support@kunbus.com.
Are you going to continue (N/y)?" -n 1 t_ant

	if [ "$t_ant" != "y" ] && [ "$t_ant" != "Y" ]; then
		echo
		exit 0
	fi
	echo
fi

echo "report generating..."
sudo sos report -o revpi,revpi-eep,revpi-codesys --batch --tmp-dir "$sos_tmp_dir" >/dev/null
sos_file=$(ls "$sos_tmp_dir"/*.tar.xz)

printReportFile(){
		echo "Your sosreport has been generated and saved in:"
		echo "$sos_file"
}

if [ "$force" != "1" ]; then
	read -rp "To make the report have better accessibility, the ownership of the report
can be changed to the current user by inheriting ownership from the containing folder.
Are you going to proceed(N/y)?" -n 1 t_ant
	if [ "$t_ant" != "y" ] && [ "$t_ant" != "Y" ]; then
		printReportFile
		exit 0
	fi
	echo
fi

sudo chown -R --reference="$sos_tmp_dir" "$sos_file"*
echo "The ownership has been inherited from the containing folder $sos_tmp_dir"
printReportFile
